### PR TITLE
Fix issue w/ snow layers

### LINKED ISSUE #1115: Snow melting throwing InvalidArgumentException
* This is due to Phasechange's recent change to construct a new data object then subtract from it.

### PR DESCRIPTION
**Pull request by Varhagna**
## Fixes
* Fixes snow melting throwing invalid argument exception in PhaseChange's melt function due to improper setting of block data.
    > * Fixes #1115

### CODE REVIEW

File: src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java [hunk 1]
```diff
@@ -407,7 +407,7 @@ public void melt(final Block b) {
 					new TempBlock(b, Material.AIR.createBlockData(), 120 * 1000L);
 				} else {
 					snow.setLayers(snow.getLayers() - 1);
```
Comment (PrimordialMoros) [inline src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java:409]: Just remove this line so it doesn't double reduce the layers. Don't reuse the same blockdata

**Review by PrimordialMoros — CHANGES_REQUESTED** [review]

**Review by ChristopherWMM — APPROVED** [review]
Awesome! 👍

**Review by Simplicitee — APPROVED** [review]
